### ISSUE TITLE
Make http requests through custom component

### ISSUE THREAD

**Issue by an3dree** [microsoft-search/pnp-modern-search-extensibility-samples#17]
Well, I'm trying to develop a custom component to be rendered via custom layout and I'm trying to make http requests inside this component, however I'm having difficulty initializing pnp/sp when passing the context or passing the service scope within the component to use sp-http

anyone knows a way to do that?

**Comment by wobba** [comment]
See https://github.com/microsoft-search/pnp-modern-search/issues/2540

**Comment by an3dree** [comment]
Thanks!
