### ISSUE TITLE
How to use the extension context in search-extensibility?

### ISSUE THREAD

**Issue by heatherzhang080** [microsoft-search/pnp-modern-search-extensibility-samples#2]
I want to use the context to get some SharePoint list items to customise my search results template. How can I do it in `registerHandlebarsCustomizations`?

**Comment by heatherzhang080** [comment]
Just realised I could do it in CustomComponent as well but how to pass in WebPartContext?

**Comment by wobba** [comment]
See https://github.com/microsoft-search/pnp-modern-search/issues/918
