### ISSUE TITLE
custom datasource sample

### ISSUE THREAD

**Issue by schlechtweg** [microsoft-search/pnp-modern-search-extensibility-samples#7]
Is it possible to add a new search provider (eg. elastic) as a custom datasource? Is there any sample or which is the right extension point for doing this?

**Comment by wobba** [comment]
There is no easy way today as an ext the two sources we have are hard coded in. That said, you can extend the approach and add more sources - as it's built to be extensible. Check the SP and Graph data sources in the v4 source code.

**Comment by FranckyC** [comment]
@schlechtweg custom data sources are not supported in this version. You can certainly add a new hard coded data source based on existing code **for your own requirements**. However, this solution main goal is to target SharePoint and Microsoft Search only. Elastic search is not in the scope.

**Comment by schlechtweg** [comment]
Thanks for the answers. Elasticsearch is only given as an example. The primary concern is that many companies already have a commercial search engine in use and want to display it in the M365.

**Comment by wobba** [comment]
@schlechtweg Assuming the reach for a provider is large enough we can accept PR's to have them added as default in the web parts. M365 is a big eco system and as OOB search (Microsoft Search) is adding in external data in different ways going forward there is no reason this project should not follow to support federation.

Ideally we would have extension to have more providers, but then we need the work done to support this. And you are free to help out 👍
