### ISSUE TITLE
Pnp Search results webpart with 4.4.0.0 version javascript is not binding 

### ISSUE THREAD

**Issue by rameshbaburanga** [microsoft-search/pnp-modern-search-extensibility-samples#9]
Hi ,

Can you please help me on binding js function in PnP search results wepart 4.4.0.0
however the same js function binding is working fine for PnP search results version 3.11.1.0

**Comment by FranckyC** [comment]
Hi @rameshbaburanga, you can't inject JavaScript code in Handlebars templatesin v4. It is blocked for security reasons. Consider to use the Script Editor Web Part instead.

**Comment by rameshbaburanga** [comment]
Hi @FranckyC ,

Can we include script editor webpart in pnp serach results webparts ?

**Comment by rameshbaburanga** [comment]
Hi @FranckyC,

Thanks for your response.

We are calling the reference of java script in pnp serach results handler bar expression. The function is available on page level which is js link captured in Content Editor webpart 

Kindly advice here.

**Comment by FranckyC** [comment]
Not sure to understand your use case. Actually if you are using the extensibility library, you can write your code directly in it and create a web component to trigger your custom function. That is the main purpose of using extensions.

**Comment by rameshbaburanga** [comment]
Hi @FranckyC ,

Thanks for your prompt response.

is it possible to have a quick call.

**Comment by FranckyC** [comment]
Not really actually, I don't do consultancy here ;)

**Comment by wobba** [comment]
@rameshbaburanga I suggest you read the docs we have at https://microsoft-search.github.io/pnp-modern-search/extensibility/ or ask in https://github.com/microsoft-search/pnp-modern-search/discussions if anyone might be able to assist you.
